# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pmapps.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('code', models.IntegerField(verbose_name='编码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('category', models.IntegerField(choices=[(0, '未选择'), (1, '电子物料'), (2, '线材'), (3, '五金'), (4, '包材'), (5, '辅料')], default=0, verbose_name='种类')),
                ('info', models.CharField(max_length=200, verbose_name='描述')),
                ('num', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '物料信息表',
                'verbose_name_plural': '物料信息表',
                'db_table': 't_material',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('order_sn', pmapps.user.models.OrderSnAutoField(editable=False, max_length=20, verbose_name='订单号')),
                ('content', models.CharField(max_length=100, verbose_name='申请用途')),
                ('is_agree', models.BooleanField(default=False, verbose_name='是否同意')),
            ],
            options={
                'verbose_name': '清单状态表',
                'verbose_name_plural': '清单状态表',
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='RequiredList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('num', models.IntegerField(verbose_name='需求数量')),
                ('state', models.IntegerField(choices=[(0, '申请中'), (1, '已审核'), (2, '备料中'), (3, '已回料')], default=0, verbose_name='物料状态')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '需求物料清单表',
                'verbose_name_plural': '需求物料清单表',
                'db_table': 't_required_list',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('employee_code', pmapps.user.models.EmployeeCodeAutoField(editable=False, max_length=20, verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.IntegerField(choices=[(0, '未选择'), (1, '开发部'), (2, '计划部'), (3, '财务部'), (4, '仓储部'), (5, '人力资源部'), (6, '生产部'), (7, '采购部')], default=0, verbose_name='部门')),
                ('account', models.CharField(max_length=20, verbose_name='账号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='手机')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='requiredlist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.RequiredList', verbose_name='物料详情'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='当前处理人'),
        ),
    ]
